# Generated by Django 3.1.2 on 2020-10-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='cv_link',
        ),
        migrations.AddField(
            model_name='about',
            name='about_link',
            field=models.URLField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
